baseURL: 
title: funRiceGenes
theme: hugo-theme-bootstrap
copyright: Copyright © 2021-{year}Wen Yao. All Rights Reserved.
defaultContentLanguage: en
defaultContentLanguageInSubdir: yes
paginate: 5
enableRobotsTXT: yes
enableEmoji: yes
blackfriday:
  hrefTargetBlank: yes
outputs:
  home:
    - HTML
    - RSS
    - JSON
taxonomies:
  category: categories
  series: series
  tag: tags